# Generated by Django 5.1.1 on 2024-10-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Drugs', 'drugs'), ('Cosmetics', 'cosmetics'), ('Food', 'food'), ('Clothing', 'clothing')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('Piece', 'piece'), ('KG', 'kg'), ('Carton', 'carton'), ('Bag', 'bag')], max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_measurements', to='product.product')),
            ],
        ),
    ]
