# Generated by Django 5.1.1 on 2024-10-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='total_quantity',
        ),
    ]
