# Generated by Django 5.1.1 on 2024-10-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_product_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitmeasurement',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drugs', 'Drugs'), ('cosmetics', 'Cosmetics'), ('food', 'Food'), ('clothing', 'Flothing')], max_length=15),
        ),
        migrations.AlterField(
            model_name='unitmeasurement',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'KG'), ('carton', 'Carton'), ('bag', 'Bag')], max_length=50),
        ),
    ]
