# Generated by Django 5.1.1 on 2024-10-03 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='remaining_quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_quantity',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
