# Generated by Django 5.1.1 on 2024-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options_alter_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(),
        ),
    ]
