# Generated by Django 5.1.1 on 2024-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_category_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
