# Generated by Django 5.1.1 on 2024-10-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productbatch_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
